### ISSUE TITLE
Port the speexdsp resampler to rust

### ISSUE THREAD

**Issue by lu-zero** [rust-av/speexdsp-rs#10]
- [x] Have a working version using [c2rust](https://github.com/immunant/c2rust).
- [x] Remove all the warnings
- [x] Refactor the structures
  - [x] Remove free/malloc
- [ ] Consider using AudioQueue

**Comment by Luni-4** [comment]
@lu-zero @est31 

What about this issue? Is the last item still valid?

**Comment by Manishearth** [comment]
We'd like to use the rust version of this crate, any rough timeline on a release? Anything we can do to help speed it up?

**Comment by lu-zero** [comment]
Depending on what you need we can prepare a release immediately. The resampler should work fine even if the code could be cleaned up further.

**Comment by Manishearth** [comment]
That would be pretty great! At some point we might want to convert a bunch of the comments to doc comments, but that doesn't have to happen immediately.

**Comment by lu-zero** [comment]
To be clear, you just need the resampler

**Comment by Manishearth** [comment]
Yeah we just need the resampler.

**Comment by lu-zero** [comment]
I'll prepare something by tomorrow, let us know if API-wise there is anything you'd like to change.

**Comment by Manishearth** [comment]
cc @khodzha 

nothing that occurs to me right now!

**Comment by khodzha** [comment]
I'm ok with the current API too

**Comment by lu-zero** [comment]
https://github.com/rust-av/speexdsp-rs/tree/master/resampler here is the version I prepared, please give it a try before I publish it.

Later I'll make the main crate use it.

**Comment by khodzha** [comment]
thanks a lot, looks good to me!

**Comment by Luni-4** [comment]
We can close this one since everything is done
