### ISSUE TITLE
reset_mem rust implementation seems broken?

### ISSUE THREAD

**Issue by khodzha** [rust-av/speexdsp-rs#52]
Hello, maybe I'm just using `reset_mem()` wrong, but when I use `reset_mem()` on newly initialized resampler's rust implementation I get this panic:

```
thread 'main' panicked at 'index out of bounds: the len is 79 but the index is 79', /home/khodzha/.cargo/git/checkouts/speexdsp-rs-313ab5030f2e9275/9cf5080/src/speex_resample.rs:1200:40
```

I made [a repo that reproduces this error](https://github.com/khodzha/speexdsp_reset_mem_test)

Also I did some digging around and it seems like this error actually stems from this `self.mem` reallocation in `reset_mem()`:
https://github.com/rust-av/speexdsp-rs/blob/9cf508045770ad92e52fe681cb01f27bd23587c8/src/speex_resample.rs#L643

For example similar allocation in `update_filter()` uses `self.buffer_size` for calculating `min_alloc_size`
https://github.com/rust-av/speexdsp-rs/blob/9cf508045770ad92e52fe681cb01f27bd23587c8/src/speex_resample.rs#L777

If I change resampler code so `reset_mem()` at least allocates like this so `self.mem` has the same length as before reset:
```rust 
self.mem = vec![0.0; self.mem_alloc_size as usize];
```
this panic doesnt appear anymore in my usecase, but I'm not sure if this is proper way to handle this

**Comment by Luni-4** [comment]
@khodzha 

Can we close this one?

**Comment by khodzha** [comment]
Yeah I think its fixed
